### ISSUE TITLE
Reload/restart method to update lists

### ISSUE THREAD

**Issue by nalabelle** [hasameli/foghorn#3]

**Comment by Dr-Syn** [comment]
Adding a signal listener for SIGHUP to trigger the existing configuration load method might be the way to approach this - now that we have an existing configuration load method.

Also, this would provide the rigging for an API-based config reload method - build the reload handler in such a way that it can receive either the SIGHUP or the API signal.

**Comment by Dr-Syn** [comment]
https://github.com/hasameli/foghorn/pull/21 handles this now
