### ISSUE TITLE
Baselining mode

### ISSUE THREAD

**Issue by nalabelle** [hasameli/foghorn#4]
designate a time for all traffic to pass through and be resolved to initially populate greylist

**Comment by Dr-Syn** [comment]
I've been mulling over this one all week - a thought occurs: perhaps this is a special case of ACLs. 

One of the features I know will be requested in the future is the ability to exempt certain systems from greylisting on all or some DNS requests - e.g. someone wants to keep the same DNS setup across the network but exempt the mailserver from greylisting on MX, TXT, SPI, etc. 

(And yes, I know we don't process those yet)

The solution here would be to have some kind of ACL whereby systems could be grouped into certain categories (workstations, mailservers, guest devices, whatever) and these categories would be granted certain rulesets.

Rather like /etc/sudoers - that's the thing that inspired this train of thought.

If we can figure out how to implement that kind of functionality, then baselining would just be a special case behavior - or possibly a prerequisite. Still pondering how these fit together, but I figured I should document it before I forget it.

**Comment by Dr-Syn** [comment]
Ah, Zack has handled this quite nicely in https://github.com/hasameli/foghorn/pull/18
