### ISSUE TITLE
API

### ISSUE THREAD

**Issue by nalabelle** [hasameli/foghorn#6]
Implement API to foghornd to allow for front ends, etc

**Comment by nalabelle** [comment]
@Dr-Syn Give us a rough outline on how you expect this to function. Need this for www side at some point.

**Comment by Dr-Syn** [comment]
Notes: have the API hook in via the plugins interface; check notebook for notes w/r/t required functions.

**Comment by Dr-Syn** [comment]
Basic API implemented; assigning documentation to self in separate issue
